package com.test.pract.yogi.basic;

public class Test {
    public static void main(String[] args) {
        int[] a = new int[3];
        int[] b = new int[6];
        int[] c = new int[7];
        System.out.println(a.length);
        System.out.println(b.length);
        System.out.println(c.length);
        System.out.println(a[0]);
        System.out.println(a[2]);
        System.out.println(b[0]);
        System.out.println(c[0]);
        int[][] d = new int[2][3];
        System.out.println(d[0]);
        System.out.println(d[0][0]);
        int[][] e = new int[4][];
        System.out.println(e);
        int[] f = new int[5];
        f[0]=10;
        f[1]=20;
        f[2]=30;
        f[3]=40;
        f[4]=50;
        System.out.println(f[0]);
        System.out.println(f[1]);
        System.out.println(f[2]);
        System.out.println(f[3]);
        System.out.println(f[4]);
        char[] ch={'a','e','i','o','u'};
        System.out.println(ch[0]);
        System.out.println(ch[1]);
        System.out.println(ch[2]);
        System.out.println(ch[3]);
        System.out.println(ch[4]);
        String[] s={"Yogeswari","Gowthami","Sravani","Joshnavi"};
        System.out.println(s[0]);
        System.out.println(s[1]);
        System.out.println(s[2]);
        System.out.println(s[3]);
        int[] x =new int[6];
        System.out.println(x.length);
        String k = "Yogeswari";
        System.out.println(k.length());
        int[][] h = new int[5][3];
        System.out.println(h.length);
        System.out.println(h[0].length);
        int[] l=new int[10];
        l[0]=100;
        l[1]='a';
        System.out.println(l[0]);
        System.out.println(l[1]);
        byte[] b1= new byte[4];
        b1[0]=4;
        b1[1]=3;
        b1[2]=2;
        b1[3]=1;
        System.out.println(b1 [0]);
        System.out.println(b1 [1]);
        System.out.println(b1 [2]);
        System.out.println(b1 [3]);
        Object[] O = new Object[20];
        O [0]=new Object[10];
        O [1]=new Object ();
        O [2]=new String ("Yogeswari");
        System.out.println(O[0]);
        System.out.println(O[1]);
        System.out.println(O[2]);
        Number[] n=new Number[10];
        n[0]=new Integer(10);
        n[1]=new Double(10.5);
        System.out.println(n[0]);
        System.out.println(n[1]);
        System.out.println(n[2]);
        int[] int1={10,20,30};
        char[] char1={'a','b','c'};
        int[] Char1=int1;
        System.out.println(int1[0]);
        System.out.println(int1[1]);
        System.out.println(int1[2]);
        System.out.println(char1[0]);
        System.out.println(char1[1]);
        System.out.println(char1[2]);
        int[] int2={10,20,30,40,50,60,70};
        int[] int3 ={80,90,100};
        a= int3;
        int3 =a;
        System.out.println(int2[0]);
        System.out.println(int2[1]);
        System.out.println(int2[2]);
        System.out.println(int2[3]);
        System.out.println(int2[4]);
        System.out.println(int2[5]);
        System.out.println(int3[0]);
        System.out.println(int3[1]);
        System.out.println(int3[2]);
    }
}